config/routes.rb
MatchaaCom::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
    match '/users/sign_out' => 'sessions#destroy'
    match '/users/sign_in' => 'sessions#create'
    match '/users/get_token' => 'sessions#new', :as => 'new_user_session'
    match '/users/create_token' => 'sessions#create_token'
  end

  resources :matches, :only => [:create, :new, :edit, :show] do
    member do
      put :finalize
    end
    collection do
      get :mine
    end
    resources :answers, :only => [:index, :new, :create]
  end

  root :to => "home#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  belongs_to :match
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :matches
  has_many :questions

  def random_questions
    questions.all.shuffle.take(10)
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_friendly_id :players_name, :use_slug => true
  belongs_to :player1, :class_name => 'User'
  belongs_to :player2, :class_name => 'User'
  belongs_to :user
  belongs_to :category
  has_many :answers
  scope :pending, where(:status => 'pending')
  scope :completed, where(:status => 'completed')

  before_create :set_tokens

  def players_name
    name
  end

  def name
    "#{player1.name} vs #{player2.name}"
  end

  def questions
    Question.find(self.question_ids.split(","))
  end

  def player1_answers
    Hash[*self.answers.where(user_id: self.player1.id).collect {|q| [q.question_id, q.body]}.flatten]
  end

  def player2_answers
    Hash[*self.answers.where(user_id: self.player2.id).collect {|q| [q.question_id, q.body]}.flatten]
  end

  def pending?
    self.status == 'pending'
  end

  def pending!
    self.update_attributes(status: 'pending')
  end

  def completed?
    self.status == 'completed'
  end

  def completed!
    self.update_attributes(status: 'completed')
  end

  def new?
    self.status == 'new'
  end

  def send_invites!
    self.pending!
    Mailer.invite(self, self.player1, self.token1).deliver
    Mailer.invite(self, self.player2, self.token2).deliver
  end

  def set_tokens
    self.token1 = ActiveSupport::SecureRandom.urlsafe_base64
    self.token2 = ActiveSupport::SecureRandom.urlsafe_base64
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :answers
  has_many :matches
  include Gravtastic
  gravtastic
  
  has_many :matches
  before_save :ensure_authentication_token

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :token_authenticatable, :trackable, :validatable

  validates_presence_of :name

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name
  attr_accessor :password

  def password_required?
    false
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :find_match
  before_filter :verify_token, :only => [:index]
  before_filter :sign_in_user, :only => [:index]
  before_filter :authenticate_user!
  after_filter :update_token, :only => [:create]
  after_filter :update_match_status, :only => [:create]

  def index
  end

  def create
    params[:answer][:questions].each do |question|
      current_user.answers.create(match: @match, question_id: question.first,  body: question.last)
    end
    flash[:notice] = "Awesome. You are a brave man"
    redirect_to match_path(@match)
  end

  def sign_in_user
    user = params[:t] == @match.token1 ? @match.player1 : @match.player2
    sign_in(:user, user)
  end

  def verify_token
    unless [@match.token1, @match.token2].include?(params[:t])
      flash[:alert] = "Your authentication token might be expired"
      redirect_to root_path 
    end
  end

  def find_match
    @match = Match.find(params[:match_id])
  end

  def update_token
    if @match.token1 == params[:answer][:t]
      @match.update_attributes(token1: nil)
    elsif @match.token2 == params[:answer][:t]
      @match.update_attributes(token2: nil)
    end
  end

  def update_match_status
     if [@match.token1, @match.token2].all? {|t| t.nil?}
       @match.completed!
     end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => [:test]
  def index
    @pending_matches  = Match.pending.order("id DESC").limit(6)
    @completed_matches = Match.completed.order("id DESC").limit(5)
  end
end

app/controllers/matches_controller.rb
class MatchesController < InheritedResources::Base
  before_filter :authenticate_user!, :only => [:new, :create, :mine]

  def show
    @player1_answers = resource.player1_answers
    @player2_answers = resource.player2_answers
    show!
  end

  def new
    @match = current_user.matches.build
  end

  def create
    @player1 = User.find_by_email(params[:match][:player1][:email]) || User.create(params[:match][:player1])
    @player2 = User.find_by_email(params[:match][:player2][:email]) || User.create(params[:match][:player2])

    @match = current_user.matches.build(player1: @player1, player2: @player2)

    if @player1.valid? && @player2.valid?
      @match.save
      redirect_to edit_match_path(@match)
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    edit!
  end

  def finalize
    category_id = params[:match][:category_id]
    resource.update_attributes(category_id: category_id, question_ids: params[:match][:category][category_id][:questions])
    resource.send_invites!
    flash[:notice] = 'Awesome! Your friends will be invited to answer the question in a bit. Meanwhile share this page with the others'
    redirect_to match_path(resource)
  end

  def mine
    @matches = current_user.matches
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def clean_up_passwords(resource)
  end

  def redirect_location(resource_name, resource)
    new_match_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create_token
    if user = User.find_by_email(params[:user][:email])
      user.reset_authentication_token!
      Mailer.token(user).deliver
      flash[:notice] =  "Please check your email to login"
    else
      flash[:alert] =  "Sorry, can't find your email'"
    end
    redirect_to new_user_session_path
  end

  def create
    if user = User.find_by_authentication_token(params[:authentication_token])
      set_flash_message(:notice, :signed_in) if is_navigational_format?
      sign_in(:user, user)
      flash[:notice] = "Welcome back!"
    else
      flash[:alert] =  "Sorry, can't sign you in"
    end
    redirect_to root_path
  end

  def destroy
    current_user.reset_authentication_token! if user_signed_in?
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def banner(match)
    render :partial => 'shared/banner', locals: { match: match } if match
  end
end

app/views/answers/index.html.haml
%h1= @match.category.name
%h4= "#{time_ago_in_words(@match.created_at)} ago"
= banner(@match)

- form_for(:answer, :url => match_answers_path(@match)) do |f|
  = f.hidden_field :authentication_token, value: params[:t]
  %table
    - @match.questions.each do |question|
      %tr
        %td
          = question.body
        %td
          - if current_user == @match.player1
            = text_area_tag "answer[questions][#{question.id}]", nil,  :rows => 3, :cols => 30
        %td
          - if current_user == @match.player2
            = text_area_tag "answer[questions][#{question.id}]", nil, :rows => 3, :cols => 30

  = f.submit

app/views/home/_banner.html.haml
%div#banner
	%div.user
		%span.user_image
		%span.user_name
	
	%div.user
		%span.user_image
		%span.user_name
		

app/views/home/index.html.haml
= banner(@pending_matches.shift)

%div.matches
  %div.box-match
    %h3 Pending Matches/In Progress
    %ul.pending
      = render :partial => @pending_matches

  %div.box-match
    %h3 Finished Matches
    %ul.completed
      = render :partial => @completed_matches

- unless user_signed_in?
  %div.divider
    %span or
  = render :partial => 'sessions/form'

%div#description
  %h1
    What's 'MATCHAA' all about?
  %span
    Matchaa allows you to pit two of your closest friends against each other in a battle of Matchaness. You will finally find out which of your friends is the most 'MATCHAA'! What are you waiting for?

app/views/layouts/application.html.haml
!!!5
%head
  %title Matchaa.com
  %link{:href => 'http://fonts.googleapis.com/css?family=Holtwood+One+SC', :rel => 'stylesheet', :type => 'text/css'}
  %link{:href => 'http://fonts.googleapis.com/css?family=Oswald', :rel => 'stylesheet', :type => 'text/css'}
  = stylesheet_link_tag 'screen', 'ie'

%body
  %header#header
    %div.page
      %h1 matchaa
      %div.login
        - unless user_signed_in?
          = form_for(:user, url: registration_path(:user) ) do |f|
            %p
              = f.text_field :name, :placeholder => 'Your Name'
            %p
              = f.email_field :email, :placeholder => 'Your Email'
            %p
              = f.submit 'Make a Match'
        - if user_signed_in?
          %span
            %strong
              = "You've logged as #{current_user.name}"
            = image_tag current_user.gravatar_url, :width => 60, :class => 'right'
          %nav
            = link_to 'Create Match', new_match_path, :class => 'submit'
            = link_to 'Sign Out', users_sign_out_path, :class => 'logout'

  %section#section
    %div.page
      - unless flash.empty?
        .notification.error
          - flash.each do |key, value|
            %h4= "#{key}: Wanted Dead or Alive "
            %p= value
      = yield

  %footer#footer
    %div.page
      %span.copyright= raw "This 'Machaa!' brought to you by #{link_to 'OSOM PEOPLES', "https://github.com/arzumy/matchaa.com/"}"


  = javascript_include_tag :defaults
  - if Rails.env.production?
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{ENV['MC_GA']}']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/matches/_match.html.haml
%li
  = image_tag match.player1.gravatar_url, width: 32, :class => 'left'
  %span
    %h4
      = link_to match.name, match_path(match)
    %em
      = "#{time_ago_in_words(match.created_at)} ago by #{match.user.name}"
  = image_tag match.player2.gravatar_url, width: 32, :class => 'right'

app/views/matches/edit.html.haml
= simple_form_for(@match, :url => finalize_match_path) do |f|
	%h1 Select Categories or Templates
	%h5 Please click image to select category
	%div.hidden
		= f.association :category, as: :radio, selected: 1
	= image_tag 'realmatcha256.png', :id => 'category_id_1'
	= image_tag 'taskmastaa256.png', :id => 'category_id_2'
	= image_tag 'matchalove256.png', :id => 'category_id_3'
	- @categories.each do |category|
		%div.category
			%h3 
				= category.name
			- questions = category.random_questions
			= f.hidden_field :question_ids, name: "match[category][#{category.id}][questions]", value: questions.map(&:id).join(',')
			%ul.questions
				- questions.each do |question|
					%li= question.body
	%div.clearfix
	= f.submit 'Submit'

app/views/matches/mine.html.haml
%ul
  - @matches.each do |match|
    %li
      = link_to match.name, match_path(match)
      = "Status: #{match.status}"

= link_to 'Create new match here', new_match_path

app/views/matches/new.html.haml
= simple_form_for(@match, :url => matches_path) do |f|
	%h1 Enter Name and  Email for Contestant
	%div.user.left
		= image_tag 'matchalove128.png', :style => 'float: left'
		= f.fields_for :player1 do |ff|
			= ff.input :name
			= ff.input :email
	%div.user.right
		= image_tag 'taskmastaa128.png', :style => 'float: left'
		= f.fields_for :player2 do |ff|
			= ff.input :name
			= ff.input :email

	= f.submit

app/views/matches/show.html.haml
= render :partial => 'shared/share', :locals => { :url => request.url }

%div.match-time
	%h1= @match.category.name
	%h5= "#{time_ago_in_words(@match.created_at)} ago"

= banner(@match)

%table
	%thead
		%tr
			%td Question
			%td(width="200") 
				= resource.player1.name
			%td(width="200") 
				= resource.player2.name
	- # TODO: we just show all answers  now regardless of status
	- @match.questions.each do |question|
		%tr
			%td
				= question.body
			%td
				= @player1_answers[question.id] unless @player1_answers.empty?
			%td
				= @player2_answers[question.id] unless @player2_answers.empty?

%div#comments
	%h1 Comments the 'Matchaa!'
	#fb-root
	%script{:src => "http://connect.facebook.net/en_US/all.js#xfbml=1"}
	%fb:comments{:href => match_url(@match), :num_posts => "10", :width => "900"}

app/views/shared/_banner.html.haml
= link_to match_path(match) do
  %div#banner
    %div.user.left
      %span.user_image
        = image_tag match.player1.gravatar_url
      %span.user_name
        = match.player1.name

    %div.user.right
      %span.user_image
        = image_tag match.player2.gravatar_url
      %span.user_name
        = match.player2.name

app/views/shared/_share.html.haml
%div.social-share
	%p Share this with other matchaas: 
	.matchaa-share-button
		%a{:href => url, :rel => '', :class => 'twitter-share-button', :'data-via' => 'fadzril', :'data-count' => 'horizontal'} Tweet
		%script{:src => 'http://platform.twitter.com/widgets.js', :type => 'text/javascript'}
	.matchaa-share-button
		#fb-root
		%script{:src => 'http://connect.facebook.net/en_US/all.js#appId=267470573266442&amp;xfbml=1'}
		%fb:like{:href => url, :send => 'true', :layout => 'button_count', :width => '150', :show_faces => 'true'}
	.matchaa-share-button.plus
		%script{:src => 'http://apis.google.com/js/plusone.js', :type => 'text/javascript'}
		%g:plusone